package com.jd.home.framework.monitor.db.jdbc.deprecated.connection;
import com.jd.home.framework.monitor.db.jdbc.deprecated.statement.PreparedStatementWrapper;
import com.jd.home.framework.monitor.db.jdbc.deprecated.statement.StatementWrapper;

import java.sql.*;

/**
 * Connection包装类
 * @author <a href=mailto:wangsongpeng@jd.com>王宋鹏</a>
 * @since 2018/01/25
 */
public class ConnectionWrapper extends AbstractConnection {


    public ConnectionWrapper(Connection connection){
      this.targetConnection = connection;
    }


    @Override
    public Statement createStatement() throws SQLException {
        return new StatementWrapper(getTargetConnection().createStatement());
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return new PreparedStatementWrapper(getTargetConnection().prepareStatement(sql));
    }

    @Override
    public void setAutoCommit(boolean autoCommit) throws SQLException {
        getTargetConnection().setAutoCommit(autoCommit);
    }

    @Override
    public boolean getAutoCommit() throws SQLException {
       return getTargetConnection().getAutoCommit();
    }

    @Override
    public void commit() throws SQLException {
         getTargetConnection().commit();
    }

    @Override
    public void rollback() throws SQLException {
         getTargetConnection().rollback();
    }

    @Override
    public void close() throws SQLException {
         getTargetConnection().close();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return getTargetConnection().isClosed();
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        return getTargetConnection().getMetaData();
    }

    @Override
    public void setReadOnly(boolean readOnly) throws SQLException {
        getTargetConnection().setReadOnly(readOnly);
    }

    @Override
    public boolean isReadOnly() throws SQLException {
        return getTargetConnection().isReadOnly();
    }

    @Override
    public void setTransactionIsolation(int level) throws SQLException {
        getTargetConnection().setTransactionIsolation(level);
    }

    @Override
    public int getTransactionIsolation() throws SQLException {
        return  getTargetConnection().getTransactionIsolation();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return getTargetConnection().getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {

    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return null;
    }

    @Override
    public void setHoldability(int holdability) throws SQLException {

    }

    @Override
    public int getHoldability() throws SQLException {
        return 0;
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return null;
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return null;
    }
}
